// <auto-generated />
using System;
using Family_and_Spa_Wellness.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Family_and_Spa_Wellness.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728045141_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Massage",
                            Description = "Targeted pressure to release deep muscle tension.",
                            DurationMinutes = 90,
                            Name = "Deep Tissue Massage",
                            Price = 145m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Massage",
                            Description = "A gentle, flowing massage to ease everyday stress.",
                            DurationMinutes = 60,
                            Name = "Swedish Relaxation Massage",
                            Price = 110m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Body",
                            Description = "Nourishing botanical wrap with essential oils.",
                            DurationMinutes = 75,
                            Name = "Aromatherapy Body Wrap",
                            Price = 120m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Body",
                            Description = "A gentle, all-over exfoliating polish that leaves skin smooth, soft, and radiant.",
                            DurationMinutes = 50,
                            Name = "Body Polish & Buff",
                            Price = 100m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Facial & Skincare",
                            Description = "Customized facial for radiant, glowing skin.",
                            DurationMinutes = 60,
                            Name = "Signature Facial",
                            Price = 95m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Facial & Skincare",
                            Description = "A collagen-boosting treatment targeting fine lines and loss of elasticity.",
                            DurationMinutes = 60,
                            Name = "Anti-Aging Collagen Facial",
                            Price = 130m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Wellness",
                            Description = "A full-body relaxation journey with lavender.",
                            DurationMinutes = 120,
                            Name = "Lavender Relaxation Ritual",
                            Price = 180m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Wellness",
                            Description = "Add a custom essential oil blend to any massage or body treatment.",
                            DurationMinutes = 15,
                            Name = "Aromatherapy Enhancement",
                            Price = 25m
                        });
                });

            modelBuilder.Entity("Family_and_Spa_Wellness.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
